import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionWrapper from "./Providers/SessionWrapper";
import { Manrope, Poppins } from "next/font/google";
import styles from "./styles.module.css";
import Navbar from "./_components/Navbar";

const inter = Inter({ subsets: ["latin"] });

const manrope = Manrope({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-manrope",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionWrapper>
        <body
          className={`${inter.className} ${manrope.variable} ${poppins.variable} ${styles.main}`}
        >
          <Theme>
            <Navbar />
            {children}
          </Theme>
        </body>
      </SessionWrapper>
    </html>
  );
}
